[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ir_pipeline_template"
version = "0.0.1"
description = ""

[tool.setuptools.packages.find]
where = ["src"]
