[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ir_pell_accepts"
version = "0.3.0"
description = "0.3.0 includes the calcs for 4/6 year grad rates and 2nd year retention rates"

[tool.setuptools.packages.find]
where = ["src"]
