# config/config.yaml
# note the use of forward slashes for file paths

#name the sections and subsections anything you want
#put their values in quotations
#access in a python script:
# 1. assume you read config file and stored it in a variable called config.
# 2. var_1_1 = config["section_1"]["subsection_1"]

section_1:
  subsection_1: "value_1_1"
  subsection_2: "value_1_2"
  
section_2:
  subsection_1: "value_2_1"
  subsection_2: "value_2_2"

